packages: []

catalogs:
  build:
    '@nuxt/devtools': ^2.6.3
    '@nuxt/icon': ^2.0.0
    '@nuxt/kit': 4.1.0
    '@vueuse/core': ^13.9.0
    '@vueuse/nuxt': ^13.9.0
    class-variance-authority: ^0.7.1
    clsx: ^2.1.1
    nuxt: 4.1.0
    tailwind-merge: ^3.3.1
    unplugin: ^2.3.10
    vite: ^7.1.4
  dev:
    '@antfu/eslint-config': ^5.2.2
    '@nuxt/eslint': ^1.9.0
    '@types/node': ^24.3.1
    eslint: ^9.34.0
    eslint-plugin-format: ^1.0.1
    oxc-parser: ^0.86.0
    typescript: ^5.9.2
    vue-tsc: ^3.0.6
  frontend:
    '@tailwindcss/vite': ^4.1.13
    motion-v: ^1.7.1
    reka-ui: ^2.5.0
    tailwindcss: ^4.1.13
    tw-animate-css: ^1.3.8
    vue: ^3.5.21
  icons:
    '@iconify-json/cib': ^1.2.3
    '@iconify-json/lucide': ^1.2.66

allowedDeprecatedVersions:
  '@types/parse-path': ^7.1.0

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - esbuild
  - unrs-resolver
  - vue-demi
